version: "2.2"
services:
  jobmanager:
    image: "flink:${FLINK_IMAGE_TAG}"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - BROKER_ADDRESS=broker:29092
      - TOPIC=ts-events
      - CONSUMER_GROUP=flink-consumer
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - /tmp/data:/data
      - /tmp/checkpoints:/checkpoints

  taskmanager:
    image: "flink:${FLINK_IMAGE_TAG}"
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - BROKER_ADDRESS=broker:29092
      - TOPIC=ts-events
      - CONSUMER_GROUP=flink-consumer
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - /tmp/data:/data
      - /tmp/checkpoints:/checkpoints
networks:
  default:
    external:
      name: kafka-flink-dash-data-pipeline-network